FROM node:13.5.0-stretch-slim
# create destination directory
RUN mkdir -p /usr/src/nuxt-app \
    && apt update && apt upgrade -y  \
    && apt install -y git bash iproute2  \
    && apt-get autoremove && apt-get clean
# copy the app, note .dockerignore
WORKDIR /usr/src/nuxt-app
COPY . /usr/src/nuxt-app/
RUN npm install && npm run build
# set app serving to permissive / assigned
ENV NUXT_HOST=0.0.0.0
# set app port
ENV NUXT_PORT=3000
ENTRYPOINT ["npm", "start"]
